# Generated by Django 5.1.2 on 2024-11-27 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_creado_alter_book_modificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 22, 23, 47, 127488)),
        ),
        migrations.AlterField(
            model_name='book',
            name='modificado',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 22, 23, 47, 127488)),
        ),
    ]
