# Generated by Django 5.1.2 on 2024-11-27 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_creado_book_modificado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('book.view', 'Puede ver los libros'), ('development', 'Permiso como Desarrollador'), ('scrum_master', 'Permiso como Scrum Master'), ('product_owner', 'Permiso como Product Owner')], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
