# Generated by Django 5.1.2 on 2024-11-25 23:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_options_alter_book_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
